// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

export type Name = string;

/** Represents the table public.kysely_migration */
export default interface KyselyMigrationTable {
  name: ColumnType<Name, Name, Name | null>;

  timestamp: ColumnType<string, string, string | null>;
}

export type KyselyMigration = Selectable<KyselyMigrationTable>;

export type NewKyselyMigration = Insertable<KyselyMigrationTable>;

export type KyselyMigrationUpdate = Updateable<KyselyMigrationTable>;
