// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type KyselyMigrationTable from './KyselyMigration';
import type KyselyMigrationLockTable from './KyselyMigrationLock';
import type UserTable from './User';

export default interface PublicSchema {
  kysely_migration: KyselyMigrationTable;

  kysely_migration_lock: KyselyMigrationLockTable;

  user: UserTable;
}
