// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

export type Id = number;

/** Represents the table public.user */
export default interface UserTable {
  id: ColumnType<Id, Id | null, Id | null>;

  email: ColumnType<string, string, string | null>;

  name: ColumnType<string, string, string | null>;

  password: ColumnType<string, string, string | null>;

  created_at: ColumnType<Date, Date | string | null, Date | string | null>;
}

export type User = Selectable<UserTable>;

export type NewUser = Insertable<UserTable>;

export type UserUpdate = Updateable<UserTable>;
