import './globals.css';
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
import type { Metadata } from 'next';
import { Analytics } from '@vercel/analytics/react';
import { getServerSession } from 'next-auth';
import Provider from '@/app/context/client-provider';
import { authOptions } from '@/app/api/auth/[...nextauth]/route';
import { redirect } from 'next/navigation';
import { CssBaseline } from '@mui/material';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  viewport: 'initial-scale=1, width=device-width',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  if (session == null) {
    return redirect('/api/auth/signin');
  }

  return (
    <html lang='en'>
      <body>
        <Provider session={session} basePath='/auth'>
          <CssBaseline />
          {children}
          <Analytics />
        </Provider>
      </body>
    </html>
  );
}
