import './globals.css'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import {Analytics} from "@vercel/analytics/react";
import {getServerSession} from "next-auth";
import Provider from "@/app/context/client-provider";
import {authOptions} from "@/app/auth/[...nextauth]/route";
import {redirect} from "next/navigation";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default async function RootLayout({
                                             children,
                                         }: {
    children: React.ReactNode
}) {
    const session = await getServerSession(authOptions)

    if (session == null) {
        return redirect("auth/signin")
    }

    return (
        <html lang="en">
        <body className={inter.className}><Provider session={session} basePath='/auth'>{children}<Analytics/></Provider>
        </body>
        </html>
    )
}
